# Generated by Django 3.1.4 on 2020-12-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=233)),
                ('first_name', models.CharField(max_length=233)),
            ],
        ),
    ]
