# Generated by Django 3.1.4 on 2020-12-16 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlist',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='userlist',
            old_name='user_name',
            new_name='username',
        ),
    ]
